version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mondb
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword


  postgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432